env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

language: node_js

node_js:
  - "7"
  - "8"
  - "9"
  - "10"

before_script:
  npm run clean

stages:
  - compile
  - test
  - deploy

jobs:
  include:
    - stage: compile
      name: "Build Tests"
      script: npm run build-test
    - script: npm run build
      name: "Build Sources"

    - stage: test
    - script: npm run test
      name: "Run Tests"

    - stage: deploy
      if: branch = master
      node_js: "10"
      script: npm run release
    - script: npx semantic-release
