language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"

env:
  - MOZ_HEADLESS=1

addons:
  firefox: latest

before_script: npm run clean && npm run build-test

jobs:
  include:
    - stage: deploy
      if: branch = master
      node_js: "10"
      script: npm run release && npx semantic-release
