language: node_js

# Skip default test
script: 'true'

jobs:
  include:
    - stage: test
      node_js:
        - "7"
        - "8"
        - "9"
        - "10"
      env:
        - MOZ_HEADLESS=1
      addons:
        firefox: latest
      script: npm run clean && npm run build-test && npm run test

    - stage: deploy
      if: branch = master
      node_js: "10"
      script: npm run release && npx semantic-release
